---
#ar0-initial-install
- hosts: all
  roles:
  - role: ar0-initial-install
    become: yes
    become_method: sudo


#ar1-cert-configuration
- hosts: initial-master-node
  roles:
  - role: ar1-cert-configuration
    become: yes
    become_method: sudo

#ar2-cert-distribution
- hosts: all:!initial-master-node
  roles:
  - role: ar2-cert-distribution
    become: yes
    become_method: sudo

#ar2-5-bootstrap-setup
- hosts: initial-master-node
  roles:
  - role: ar2-5-bootstrap-setup
    become: yes
    become_method: sudo

#ar3-xpack-p1
- hosts: all
  roles:
  - role: ar3-xpack-p1
    become: yes
    become_method: sudo

#ar4-account-setup
- hosts: initial-master-node
  roles:
  - role: ar4-account-setup
    become: yes
    become_method: sudo

#ar5-xpack-p2
- hosts: all
  roles:
  - role: ar5-xpack-p2
    become: yes
    become_method: sudo

#ar6-data-disk-config
- hosts: data-nodes
  roles:
  - role: ar6-data-disk-config
    become: yes
    become_method: sudo

#ar7-azure-plugin
- hosts: all
  roles:
  - role: ar7-azure-plugin
    become: yes

#ar8-verification
- hosts: initial-master-node
  roles:
  - role: ar8-verification
