# This Workflow builds and pushes all the images in the archetype repository
name: post-merge-archetype-management

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single job package as we need a shared folder bettween the setps for the helm charts packed
  pack:
    env:      
      IMAGE_REPOSITORY_PASSWORD: ${{ secrets.IMAGE_REPOSITORY_PASSWORD }}
      IMAGE_REPOSITORY_USERNAME: ${{ secrets.IMAGE_REPOSITORY_USERNAME }}
      IMAGE_REPOSITORY_SP_ID: ${{ secrets.IMAGE_REPOSITORY_SP_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      CI_ACR_NAME: ${{ secrets.CI_ACR_NAME }}
    runs-on: ubuntu-latest
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Create temp folders
      run: mkdir -p ${{ runner.temp }}/charts
    # Creates the .tgz for each helm chart in the repository
    - name: Pack helm charts
      env:
        HELM_TEMP_PACKAGED:  ${{ runner.temp }}/charts
      run: |
        for file in $GITHUB_WORKSPACE/charts/*
        do
          helm package $file -d $HELM_TEMP_PACKAGED
        done
              
    #Login to az cli so we can push the charts
    - name: Az login
      run: az login --service-principal --username $IMAGE_REPOSITORY_USERNAME --password $IMAGE_REPOSITORY_PASSWORD  --tenant $AZURE_TENANT_ID
      
    #Push the helm charts to CI_ACR
    - name: Push helm charts
      env:
        HELM_TEMP_PACKAGED:  ${{ runner.temp }}/charts
      run: |
        for file in $HELM_TEMP_PACKAGED/*
        do
          echo "pushing $file"
          az acr helm push --name $CI_ACR_NAME $file --force 
        done
