---
apiVersion: c12.microsoft.com/v1
kind: ApplicationConfig
metadata:
  name: sample-app-nodejs
spec:
  archetype:
    name: simple-webservice
    version: 1.0.0

  # Common to all Deployment Groups and Clusers
  parameters:
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: false
    replicas: 2


  deployment-groups:
    - name: dev

      application:
        version: $app_version

      archetype:
        version: 0.1.0

      # Common to all Clusers in this Deployment Group
      parameters:
        replicas: 2

      clusters:
        - name: $aks_name
          # Specific to this cluster
          parameters:
            replicas: 2

      connectivity: []
