
- name: Create Data Disk Partition (1/2)
  parted:
    device: /dev/sdc
    label: gpt
    number: 1
    state: present
    part_type: primary
    part_start: 0GB
    part_end: "{{ ES_DATA_DISK_SIZE }}"

- name: Create Data Disk Partition (2/2)
  filesystem:
    dev: /dev/sdc1
    fstype: ext4

- name: Create Data Directory
  file:
    path: "{{ ES_DATA_PATH }}"
    state: directory

- name: Mount Data Disk to Data Directory
  mount:
    path: "{{ ES_DATA_PATH }}"
    fstype: ext4
    src: /dev/sdc1
    state: mounted

- name: Copy Data Directory To New Location
  copy:
    src: /var/lib/elasticsearch/
    dest: /data/elasticsearch
    owner: elasticsearch
    group: elasticsearch
    remote_src: yes
    mode: preserve

- name: Update Data Directory in Elasticsearch Config
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^path\.data'
    line: 'path.data: "/data/elasticsearch"'

- name: Restart Elasticsearch
  service:
    name: elasticsearch.service
    state: restarted

- name: Restart server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true