{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helloazuregov.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helloazuregov.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.ingress.host | quote }}
  path: {{ .Values.ingress.path | quote }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - host: website.azure-gov-demo.cloudfitdsop.com
      routerName: router
      wildcardPolicy: None    
{{- end }} 
