/*
@TargetNode='localhost'
@GeneratedBy=Microsoft
@GenerationDate=03/09/2023 13:59:47
@GenerationHost=Microsoft
*/

instance of MSFT_nxScriptResource as $MSFT_nxScriptResource1ref
{
ResourceID = "[nxScript]EmptyDsc";
 GetScript = "#!/bin/bash\necho emptyGet";
 TestScript = "#!/bin/bash\nexit 0";
 SourceInfo = "D:\\build-linux-config.ps1::93::9::nxScript";
 SetScript = "#!/bin/bash\necho emptySet";
 ModuleName = "nx";
 ModuleVersion = "1.0";

 ConfigurationName = "LinuxBaseLine";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";


                        MinimumCompatibleVersion = "1.0.0";


                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};


                        Author="Microsoft";


                        GenerationDate="03/09/2023 13:59:47";


                        GenerationHost="Microsoft";


                        Name="LinuxBaseLine";


                    };
