---

- name: non_root_pods
  CRD:
    kind: NonRootPods
  properties: []
  match:
    kinds:
      - Pod
    apiGroups: []

- name: acceptable_subject_kind_in_rolebindings
  CRD:
    kind: acceptablesubjectkindinrolebindings
  properties:
    - name: allowedsubjectkinds
      default: ["Group"]
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - RoleBinding
    apiGroups: ["rbac.authorization.k8s.io"]

- name: storage_classes_customer_managed_keys
  CRD:
    kind: encryptionatrest
  properties: []
  match:
    kinds:
      - PersistentVolumeClaim
    apiGroups: []


- name: allow-privilege-escalation
  CRD:
    kind: K8sPSPAllowPrivilegeEescalation
  properties: []
  match:
    kinds:
      - Pod
    apiGroups: []
- name: apparmor
  CRD:
    kind: K8sPSPAppArmor
  properties:
    - name: allowedProfiles
      default: [ runtime/default ]
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: capabilities
  CRD:
    kind: K8sPSPCapabilities
  properties:
    - name: allowedCapabilities
      default: []
      definition:
        type: array
        items:
          type: string
    - name: requiredDropCapabilities
      default: []
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: flexvolume-drivers
  CRD:
    kind: K8sPSPFlexVolumes
  properties:
    - name: allowedFlexVolumes
      default: []
      definition:
        type: array
        items:
          type: object
          properties:
            driver:
              type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: forbidden-sysctls
  CRD:
    kind: K8sPSPForbiddenSysctls
  properties:
    - name: forbiddenSysctls
      default:
        - kernel.*
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: fsgroup
  CRD:
    kind: K8sPSPFSGroup
  properties:
    - name: rule
      default: MayRunAs
      definition:
        type: string
    - name: ranges
      default:
        - min: 1
          max: 1000
      definition:
        type: array
        items:
          type: object
          properties:
            min:
              type: integer
            max:
              type: integer
  match:
    kinds:
      - Pod
    apiGroups: []
- name: host-filesystem
  CRD:
    kind: K8sPSPHostFilesystem
  properties:
    - name: allowedHostPaths
      default: []
      definition:
        type: array
        items:
          type: object
          properties:
            readOnly:
              type: boolean
            pathPrefix:
              type: string
  match:
    kinds:
      - Pod
  apiGroups: []
- name: host-namespaces
  CRD:
    kind: K8sPSPHostNamespace
  properties: []
  match:
    kinds:
      - Pod
    apiGroups: []
- name: host-network-ports
  CRD:
    kind: K8sPSPHostNetworkingPorts
  properties:
    - name: hostNetwork
      default: false
      definition:
        type: boolean
    - name: min
      default: 1024
      definition:
        type: integer
    - name: max
      default: 16345
      definition:
        type: integer
  match:
    kinds:
      - Pod
    apiGroups: []
- name: privileged-containers
  CRD:
    kind: K8sPSPPrivilegedContainer
  properties: []
  match:
    kinds:
      - Pod
    apiGroups: []
- name: proc-mount
  CRD:
    kind: K8sPSPProcMount
  properties:
    - nmame: procMount
      default: Default
      definition:
        type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: read-only-root-filesystem
  CRD:
    kind: K8sPSPReadOnlyRootFilesystem
  properties: []
  match:
    kinds:
      - Pod
    apiGroups: []
- name: seccomp
  CRD:
    kind: K8sPSPSeccomp
  properties:
    - name: allowedProfiles
      default:
        - runtime/default
        - docker/default
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: selinux
  CRD:
    kind: K8sPSPSELinux
  properties:
    - name: allowedSELinuxOptions
      default:
        level: s0:c123,c456
        role: object_r
        type: svirt_sandbox_file_t
        user: system_u
      definition:
        type: object
        properties:
            level:
                type: string
            role:
                type: string
            type:
                type: string
            user:
                type: string
  match:
    kinds:
      - Pod
    apiGroups: []
- name: users
  CRD:
    kind: K8sPSPAllowedUsers
  properties:
    - name: runAsUser
      default:
        rule: MustRunAs
        ranges:
          - min: 1000
            max: 2000
      definition:
        type: object
        properties:
          rule:
            type: string
          ranges:
            type: array
            items:
              type: object
              properties:
                min:
                  type: integer
                max:
                  type: integer
  match:
    kinds:
      - Pod
    apiGroups: []
- name: volumes
  CRD:
    kind: K8sPSPVolumeTypes
  properties:
    - name: volumes
      default:
        - "*"
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - Pod
    apiGroups: []
    apiGroups: []
  
- name: aso_allowed_locations
  CRD:
    kind: asoallowedlocations
  properties:
    - name: allowedlocations
      default: ["northeurope"]
      definition:
        type: array
        items:
          type: string
  match:
    kinds:
      - APIMgmtAPI
      - ApimService
      - AppInsights
      - AzureLoadBalancer
      - AzureNetworkInterface
      - AzurePublicIPAddress
      - AzureSqlDatabase
      - AzureSqlFailoverGroup
      - AzureSqlServer
      - AzureVirtualMachineExtension
      - AzureVirtualMachine
      - AzureVMScaleSet
      - BlobContainer
      - CosmosDB
      - EventhubNamespace
      - Eventhub
      - KeyVaultKey
      - KeyVault
      - MySQLServer
      - PostgreSQLServer
      - RedisCache
      - ResourceGroup
      - StorageAccount
      - VirtualNetwork
    apiGroups: ["azure.microsoft.com"]

- name: deny_deployments_to_namespace
  CRD:
    kind: denydeploymentstonamespace
  properties:
    - name: namespacestodeny
      default: ["default"]
      definition:
        type: array
        items:
          type: string
  match:
    kinds: ["*"]
    apiGroups: ["*"]
