---
apiVersion: c12.microsoft.com/v1
kind: ClusterConfig
metadata:
  name: $cluster_name
spec:
  location: northeurope

  registry:
    docker:
      url: $docker_registry_url
    helm:
      url: $helm_registry_url

  kubernetes:
    url: $kubernetes_api_url

