#
# Module manifest for module 'WindowsDefenderDsc'
#
# Generated by: Jason Walker
#
# Generated on: 3/22/2018
#

@{
    # Version number of this module.
    ModuleVersion     = '2.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop')

    # ID used to uniquely identify this module
    GUID              = 'b6a20f15-7090-4aa1-a0be-921b5e8eb50b'

    # Author of this module
    Author            = 'Jason Walker'

    # Company or vendor of this module
    CompanyName       = 'Microsoft Corporation'

    # Copyright statement for this module
    Copyright         = '(c) 2018 Microsoft. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Manages the security mitigations available in the Windows Defender Security Center'

    # Minimum version of the Windows PowerShell engine required by this module

    PowerShellVersion = '5.1'

    # DSC resources to export from this module
    DscResourcesToExport = @('ProcessMitigation')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('DSC','ProcessMitigation','DesiredStateConfiguration','DSCResource')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/jcwalker/WindowsDefenderDsc/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/jcwalker/WindowsDefenderDsc'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
