/*
@TargetNode='localhost'
@GeneratedBy=Microsoft
@GenerationDate=02/02/2021 23:10:11
@GenerationHost=Microsoft
*/

instance of MSFT_nxScriptResource as $MSFT_nxScriptResource1ref
{
ResourceID = "[nxScript]EmptyDsc";
 GetScript = "#!/bin/bash\necho emptyGet";
 TestScript = "#!/bin/bash\nexit 0";
 SourceInfo = "C:\\dev\\project-chairlift\\linux\\linux-configurations.ps1::99::9::nxScript";
 SetScript = "#!/bin/bash\necho emptySet";
 ModuleName = "nx";
 ModuleVersion = "1.0";
 ConfigurationName = "LinuxBaseLine";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";
 
                        MinimumCompatibleVersion = "1.0.0";
 
                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 
                        Author="Microsoft";
 
                        GenerationDate="02/02/2021 23:10:11";
 
                        GenerationHost="Microsoft";
 
                        Name="LinuxBaseLine";

                    };

