[ClassVersion("0.9.0.0"), FriendlyName("ActiveDirectoryAuditRuleEntry")]
class ActiveDirectoryAuditRuleEntry : OMI_BaseResource
{
    [Key, Description("Indicates the Distinguished Name value for the target Active Directory Object.")] String DistinguishedName;
    [Required, Description("Indicates the access control information in the form of an array of instances of the ActiveDirectoryAuditRuleList CIM class."), EmbeddedInstance("ActiveDirectorySystemAccessControlList")] String AccessControlList[];
    [Write, Description("Indicates whether the rights defined should be enforced. Will remove any rights not explicitly defined in the configuration for the path.")] Boolean Force;
};

[ClassVersion("0.9.0.0")]
class ActiveDirectoryAuditRule
{
    [Required, Description("Specifies the conditions for auditing attempts to access a securable object."), ValueMap{"Success","Failure"}, Values{"Success","Failure"}] String AuditFlags;
    [Required, Description("Specifies the access rights that are assigned to an Active Directory Domain Services object."), ValueMap{"AccessSystemSecurity","CreateChild","Delete","DeleteChild","DeleteTree","ExtendedRight","GenericAll","GenericExecute","GenericRead","GenericWrite","ListChildren","ListObject","ReadControl","ReadProperty","Self","WriteDacl","WriteOwner","WriteProperty"}, Values{"AccessSystemSecurity","CreateChild","Delete","DeleteChild","DeleteTree","ExtendedRight","GenericAll","GenericExecute","GenericRead","GenericWrite","ListChildren","ListObject","ReadControl","ReadProperty","Self","WriteDacl","WriteOwner","WriteProperty"}] String ActiveDirectoryRights[];
    [Write, Description("Specifies if, and how, ACE information is applied to an object and its descendents."), ValueMap{"1","4","2","0","3"}, Values{"All","Children","Descendents","None","SelfAndChildren"}] String InheritanceType;
    [Write, Description("Specifies the schema GUID of the object to which the audit rule applies.")] String ObjectType;
    [Write, Description("Specifies the object type name that identifies the type of child object that can inherit this access rule.")] String InheritedObjectType;
    [Required, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
};

[ClassVersion("0.9.0.0")]
class ActiveDirectorySystemAccessControlList
{
    [Required, Description("Indicates the identity of the principal.")] String Principal;
    [Write, Description("Indicates whether the rights for this principal should be forced. Will remove any rights not explicitly defined in the configuration for the principal.")] Boolean ForcePrincipal;
    [Required, Description("Indicates the access control entry in the form of an array of instances of the AccessControlList CIM class."), EmbeddedInstance("ActiveDirectoryAuditRule")] String AccessControlEntry[];
};
