apiVersion: constraints.gatekeeper.sh/v1beta1
kind: acceptablesubjectkindinrolebindings
metadata:
  name: "acceptablesubjectkindinrolebindings"
spec:
  match:
    kinds:
      - apiGroups: 
        - "rbac.authorization.k8s.io"
        kinds:
        - "RoleBinding"
        
  parameters:
    allowedsubjectkinds: ['Group']
