apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.8.1
  image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        imagePullSecrets:
        - name: regcred      
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.8.1
  image: docker.elastic.co/kibana/kibana:7.8.1
  count: 1
  elasticsearchRef:
    name: elastic
  podTemplate:
    spec:
      imagePullSecrets:
      - name: regcred      
