---
- name: Check If CA File Exists
  stat:
    path: /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_CA.p12
  register: ca_result

- name: Check If Certificate File Exists
  stat:
    path: /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12
  register: cert_result

- name: Rename Old CA if Exists
  command: mv /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_CA.p12 /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_CA.p12.{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}
  when: ca_result.stat.exists == True

- name: Rename Old Certificate if Exists
  command: mv /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12 /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12.{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}
  when: cert_result.stat.exists == True

- name: Generate CA on Master Node
  command: /usr/share/elasticsearch/bin/elasticsearch-certutil ca --out /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_CA.p12 --pass {{ ES_INITIAL_MASTER_CA_PASS }}

- name: Genterate Certificate on Master Node
  command: /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca {{ ES_INITIAL_MASTER_HOSTNAME }}_CA.p12 --ca-pass {{ ES_INITIAL_MASTER_CA_PASS }} --out {{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12 --pass ''

- name: Move Certificate File To /etc/elasticsearch on Master Node
  copy: 
    src: /usr/share/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12
    dest: /etc/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
    remote_src: yes

- name: Copy Certificate File From Master Node to Initial Box
  fetch:
    src: /etc/elasticsearch/{{ ES_INITIAL_MASTER_HOSTNAME }}_cert.p12
    dest: /etc/elasticsearch/certs/