[ClassVersion("1.0.0.0"), FriendlyName("KeyValuePairFile")]
class DSR_KeyValuePairFile : OMI_BaseResource
{
  [Key, Description("The path to the key value pair text file.")] String Path;
  [Key, Description("The name of the key.")] String Name;
  [Write, Description("Specifies the if the key value pair with the specified key should exist in the file."),ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [Write, Description("Specifies the value type to use as the replacement string. Defaults to 'Text'."),ValueMap{"Text", "Secret"},Values{"Text", "Secret"}] String Type;
  [Write, Description("The text to replace the value with in the identified key. Only used when Type is set to 'Text'.")] String Text;
  [write, Description("The secret text to replace the value with in the identified key. Only used when Type is set to 'Secret'."),EmbeddedInstance("MSFT_Credential")] String Secret;
  [Write, Description("Ignore the case of the name of the key. Defaults to $False.")] Boolean IgnoreNameCase;
  [Write, Description("Ignore the case of any text or secret when determining if it they need to be updated. Defaults to $False.")] Boolean IgnoreValueCase;
  [Write, Description("Specifies the file encoding. Defaults to ASCII"),ValueMap{"ASCII", "BigEndianUnicode", "BigEndianUTF32", "UTF8", "UTF32"},Values{"ASCII", "BigEndianUnicode", "BigEndianUTF32", "UTF8", "UTF32"}] String Encoding;
};
